### ISSUE TITLE
Wizard for creating TIE-GT projects

### ISSUE THREAD

**Issue by RolandKluge** [eMoflon/emoflon-tie-gt#14]
What should be contained:

- [ ] proper .project file
- [ ] .mpf and .mcf file with correct import and using directives (Functionality for creating these files already exists...)

**Comment by davidgiessing** [comment]
this is existing. New -> Other ... -> eMoflon -> New TIE GT Project.
However we need to take a look at it

**Comment by RolandKluge** [comment]
Works nicely.
