### ISSUE TITLE
Create validation/code completion rule that forbids the usage of "refine" for TIE-GT

### ISSUE THREAD

**Issue by RolandKluge** [eMoflon/emoflon-tie-gt#2]

**Comment by anthonyanjorin** [comment]
What does this mean exactly?  You also can't refine on pattern level?  Why not just use the flattened versions of the patterns?

**Comment by RolandKluge** [comment]
Is there a method that takes an EditorPattern  and returns a flattened EditorPattern?
If yes, we could use this for TIE-GT as well.

**Comment by anthonyanjorin** [comment]
Yes, I believe so.  Based on our rather disappointing measurements for TGGs, Patrick simply used the flattened version of all patterns and basically "ignored" refinements.  This is exactly what you want/need.

**Comment by anthonyanjorin** [comment]
FYI @patrickrobrecht

**Comment by RolandKluge** [comment]
OK, we will try this at a later point in time.
Follow-up: https://github.com/eMoflon/emoflon-tie-gt/issues/4
