### ISSUE TITLE
Create validation/code completion rule that forbids the usage of "or" in when clauses of patterns

### ISSUE THREAD

**Issue by RolandKluge** [eMoflon/emoflon-tie-gt#3]
The codegenerator does not support logical AND/OR of pattern invocations at the moment

**Comment by davidgiessing** [comment]
@RolandKluge couldn't we just remove the AND part from xtext in our branch?

**Comment by RolandKluge** [comment]
> couldn't we just remove the AND part from xtext in our branch?

We want to be fully compatible with IBeX on the grammar level.
Therefore, this is not an option, unfortunately.

**Comment by davidgiessing** [comment]
I implemented this now in our branch of ibex as validation rule, but I do not have commit rights @RolandKluge

**Comment by RolandKluge** [comment]
Which of the IBeX projects is it?
You appear to have push rights in "ibex-democles" and "ibex"

**Comment by RolandKluge** [comment]
Works.
