### ISSUE TITLE
Fix Formatter for .mcf files

### ISSUE THREAD

**Issue by davidgiessing** [eMoflon/emoflon-tie-gt#42]
The Formatter does not seem to work for .mcf files. I always get: ERROR [formatting2.ContentFormatter$FormattingUnitOfWork::95] - Error formatting platform:/resource/test2/src/test.mcf: null

**Comment by RolandKluge** [comment]
The problem is obviously that not all parts of the grammar are supported. If I remove everything but the 'this' statement in each operation, the formatter completes at least.

**Comment by RolandKluge** [comment]
Solved in 9fe0842
