### ISSUE TITLE
Add synthesized CF variables if not all editor parameters/nodes are bound

### ISSUE THREAD

**Issue by RolandKluge** [eMoflon/emoflon-tie-gt#6]
Currently, the code generation fails if an editor parameter/node is not bound in the parameter list of a pattern statement.

To increase robustness, we should create synthesized CF variables in the background and assign these variables to the editor parameter/node.

**Comment by davidgiessing** [comment]
This should be resolved by now but need to check back

**Comment by RolandKluge** [comment]
Checked.
